export const userRegistersSectionMock = [
  {
    condutor: "João",
    habilitação: "123456789",
    categoria: "B",
    vencimento: "2025-12-31",
    nome: "João da Silva",
    documento: 123456789,
    tipo: "CPF",
    logradouro: "Rua das Flores",
    número: "123",
    cidade: "São Paulo",
    uf: "SP",
    bairro: "Centro",
    Início: "2023-06-26",
    motivo: "Viagem a trabalho",
    observação: "Nenhuma observação",
    quilometragem: 5000,
    controle: "Controle de Qualidade",
    idCondutor: "A123",
    idVeiculo: "V456",
    idCliente: "C789",
    placa: "ABC1234",
    fabricado: 2020,
    modelo: "Fiat Palio",
    rodagem: 10000
  },
  {
    condutor: "João",
    habilitação: "123456789",
    categoria: "B",
    vencimento: "2025-12-31",
    nome: "João da Silva",
    documento: 123456789,
    tipo: "CPF",
    logradouro: "Rua das Flores",
    número: "123",
    cidade: "São Paulo",
    uf: "SP",
    bairro: "Centro",
    Início: "2023-06-26",
    motivo: "Viagem a trabalho",
    observação: "Nenhuma observação",
    quilometragem: undefined,
    controle: "Controle de Qualidade",
    idCondutor: "A123",
    idVeiculo: "V456",
    idCliente: "C789",
    placa: "ABC1234",
    fabricado: 2020,
    modelo: "Fiat Palio",
    rodagem: 10000
  },
]
